---
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - '../vars/default.yaml'
    - '../vars/regions.yaml'

  tasks:
    - name: Deploy cloudtrail on all AWS regions per each profile
      cloudformation:
        stack_name: "{{ stack_id }}"
        state: "{{ state }}"
        template: "{{ cfn_templates }}/cloudtrail.json"
        region: "{{ item.region }}"
        template_parameters:
          BucketName: "{{ bucket_name }}"
      with_items: "{{ regions }}"
      register: stack
    - debug: var=stack

