---
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - '../vars/default.yaml'
    - '../vars/regions.yaml'
    - '../vars/profiles.yaml'

  tasks:
    - name: Deploy cloudtrail on all AWS regions per each profile
      cloudformation:
        stack_name: "{{ stack_id }}"
        state: "{{ state }}"
        profile: "{{ profile_name }}"
        template: "cloudtrail.json"
        region: {{ item.region }}
        with_items: regions
        template_parameters:
          BucketName: {{ bucket_name }}
      register: stack

    - debug: var=stack.stack_outputs

